version: '3'

services:
  tensorus-api:
    build: .
    container_name: tensorus-api
    ports:
      - "8000:8000"
    volumes:
      - tensorus-data:/data/tensorus
    environment:
      - TENSORUS_STORAGE_PATH=/data/tensorus
    command: python run_api.py --host 0.0.0.0 --port 8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  tensorus-dashboard:
    build: .
    container_name: tensorus-dashboard
    ports:
      - "8501:8501"
    volumes:
      - tensorus-data:/data/tensorus
    environment:
      - TENSORUS_STORAGE_PATH=/data/tensorus
    command: python run_dashboard.py
    restart: unless-stopped
    depends_on:
      - tensorus-api

volumes:
  tensorus-data:
    driver: local 